apiVersion: v1
kind: Service # the workload resource
metadata:
  name: hello-node-service # name of the service
spec:
  type: ClusterIP # Exposes the Service on a cluster-internal IP
  selector: # REQUIRED: define how this service finds which pods to manage
    app: hello-node # key and value of the label identifying pods
  ports:
    - port: 8080 # port of the service
      targetPort: 8080 # port targeted on the pod
